### ISSUE TITLE
Error 500 on rest/settings/sync

### ISSUE THREAD

**Issue by moshthepitt** [OpenSRP/opensrp-server-web#490]
Encountering an error 500  from the rest/settings/sync endpoint.

My expectation is that we should not encounter 500 level errors but instead receive back 4xx level responses notifying us of the error.

### Request details

Request URL: https://reveal-stage.smartregister.org/opensrp/rest/settings/sync
Request Method: POST

Request body is attached.

[settings.json.zip](https://github.com/OpenSRP/opensrp-server-web/files/5055769/settings.json.zip)

**Comment by dubdabasoduba** [comment]
@moshthepitt @githengi It might be something that's affecting the Malawi server too. Looking at it.  now.

**Comment by moshthepitt** [comment]
I suspect that my example above is failing because the payload is large.  But, alas, with the way this works on the web app we need to be able to handle large payloads.

**Comment by dubdabasoduba** [comment]
I don't think it's the large payload. From the little investigation I have done it affects the global settings. The setting payload you are sending is a global one since it's not tied to any `teamId`, `locationId`, `providerId` or `team`

**Comment by dubdabasoduba** [comment]
@moshthepitt When do you need this?

**Comment by moshthepitt** [comment]
ASAP but can wait mid next week

**Comment by dubdabasoduba** [comment]
Fixed in  [v2.2.23-SNAPSHOT](https://github.com/OpenSRP/opensrp-server-web/releases/tag/v2.2.23-SNAPSHOT) and [v2.1.46-SNAPSHOT](https://github.com/OpenSRP/opensrp-server-web/releases/tag/v2.1.46-SNAPSHOT)

**Comment by moshthepitt** [comment]
Seems like it is [still happening](https://github.com/onaio/reveal-frontend/issues/1120)

**Comment by dubdabasoduba** [comment]
**Identified problem**

- The insert many query is breaking because the payload surpassed the 32767 bind variables limit per statement on Postgres. 

**Optimal workaround**
- Batch the inserts to the database

**Comment by dubdabasoduba** [comment]
> I suspect that my example above is failing because the payload is large. But, alas, with the way this works on the web app we need to be able to handle large payloads.
@moshthepitt was right on this. The previous issue fixed wasn't the root cause in this case.
